name: Python application

on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Upgrade pip and install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-root
    - name: pre-commit
      run: |
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest --cov-report=term
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        name: andoku-sudoku-loader-codecov
        fail_ci_if_error: true
